server:
  port: 9000

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/aardelean/config-server
        health:
          repositories:
            eureka:
              label: master
  profiles:
    active: dev

